[package]
name = "noftp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.9.0"
local-ip-address = "0.5.3"
native-dialog = "0.6.3"
regex = "1.8.1"
toml = "0.7.3"
